# Generated by Django 5.1.7 on 2025-03-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_title', models.CharField(max_length=20)),
                ('content_description', models.TextField(max_length=102)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_type', models.CharField(max_length=20)),
                ('subscription_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_start_date', models.DateTimeField(null=True)),
                ('subscription_end_date', models.DateTimeField(null=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pear_monie.customers')),
            ],
        ),
    ]
